## .github/ISSUE_TEMPLATE/config.yml

blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://github.com/OneInX-Lab/BladeInsight/blob/main/SUPPORT.md
    about: Usage and support.
  - name: Security
    url: https://github.com/OneInX-Lab/BladeInsight/blob/main/SECURITY.md
    about: Security reporting policy.
  - name: Security Advisory
    url: https://github.com/OneInX-Lab/BladeInsight/security/advisories/new
    about: Private vulnerability report.
  - name: Feature Request
    url: https://github.com/OneInX-Lab/BladeInsight/issues/new?template=feature_request.md
    about: Submit feature request.